name: Deploy MkDocs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Supprimer les liens symboliques
        run: rm -rf airflow/logs/dag_processor/latest

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: pip install mkdocs-material

      - name: Deploy avec .nojekyll
        run: |
          mkdocs gh-deploy --force
          git checkout gh-pages
          touch .nojekyll
          git add .nojekyll
          git commit -m "Add .nojekyll" || exit 0
          git push origin gh-pages
