name: ci

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Remove problematic symlink
        run: rm -rf airflow/logs/dag_processor/latest
      - run: pip install mkdocs-material
      - run: mkdocs build
      - name: Create .nojekyll
        run: touch ./site/.nojekyll
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./site
      - uses: actions/deploy-pages@v4
