jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Supprimer les liens symboliques
        run: rm -rf airflow/logs/dag_processor/latest

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: pip install mkdocs-material
      - run: mkdocs build --strict

      - name: Créer .nojekyll
        run: touch ./site/.nojekyll

      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
