name: ci

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Nettoyer les liens symboliques
        run: |
          rm -rf airflow/logs/dag_processor/latest
          rm -rf ./site  # Nettoyer les builds précédents

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: pip install mkdocs-material
      - run: mkdocs build

      - name: Créer .nojekyll
        run: touch ./site/.nojekyll

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./site  # Cibler uniquement le dossier de build
          exclude: |
            **/airflow/
            **/logs/
            **/models/
            **/notebooks/
