# Use postgres/example user/password credentials

services:
  mlflow:
    image: ubuntu/mlflow:2.1.1_1.0-22.04_stable
    container_name: mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=postgresql://${MLFLOW_DB_USER}:${MLFLOW_DB_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${MLFLOW_DB}
    volumes:
      - ./mlflow:/mlflow
    command: mlflow server --host
    networks:
      - airflow-default
