name: reco_movies
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10 # Python 3.12 incompatible avec ces versions
  - numpy=1.26.4
  - seaborn=0.12.2
  - jupyter
  - pip
  - pip:
      - matplotlib==3.7.4
      - scikit-learn==1.3.2
      - pandas==2.1.3
