name: Deploy MkDocs

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write # Obligatoire pour les déploiements Pages modernes

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Nécessaire pour les déploiements Pages modernes

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: pip install mkdocs-material mkdocs-mermaid2-plugin
      - run: mkdocs build --strict

      - name: Créer .nojekyll
        run: touch ./site/.nojekyll

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
