name: Deploy MkDocs

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Supprimer les liens symboliques
        run: rm -rf airflow/logs/dag_processor/latest

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: pip install mkdocs-material
      - run: mkdocs build --strict

      - name: Créer .nojekyll
        run: touch ./site/.nojekyll

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./site
          exclude: |
            **/airflow/
            **/logs/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
